In [1]:
import lfox
import lfox.lattice as lat
import jax
import jax.numpy as jnp

import numpy as np

In [2]:
d = 4
L = 16

In [3]:
MyLat = lat.SquareLattice(dims=((L,)*d))
MyLat

In [4]:
phi_field = lat.LatticeField(MyLat)
phi_field.field = np.ones_like(phi_field.field)
phi_field.field[0,0] = 0.
phi_field.field = jnp.array(phi_field.field)
print(phi_field.field, phi_field)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  ...

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 

In [5]:
phi_field.nn_field(0)

Array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
    

In [6]:
p2 = phi_field.copy()
p2 += phi_field
p2.field

Array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.]],

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.]],

        ...,

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
    

In [7]:
print(p2)
p2 += phi_field
print(p2, p2.field)

<lfox.lattice.LatticeField object at 0x105a79310> [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  ...

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...


In [8]:
@jax.jit
def scalar_action(phi):
    S = 0.0
    F = phi.field
    for ax in range(d):
        S -= 2 * jnp.sum(F * phi.nn_field(ax))
    phi2 = F**2
    S += jnp.sum(phi2)
    S += jnp.sum( (phi2-1)**2 )

    return S

In [9]:
sum(jnp.array([1,2]), jnp.array([3,4]))

Array([6, 7], dtype=int32)

In [10]:
%time scalar_action(phi_field)

CPU times: user 81 ms, sys: 12.3 ms, total: 93.4 ms
Wall time: 81.7 ms


Array(-455680., dtype=float32)

In [11]:
import lfox.evolution.hmc as lhmc

In [12]:
itest = lhmc.LeapfrogIntegrator(0.02, 50)
print(itest)

In [13]:
class ScalarAction(lhmc.Action):
    @staticmethod
    def _Sjax(phi):
        return scalar_action(phi)

    def _compute_forces(self):
        self.grads = {
            'phi': jax.jit(jax.grad(scalar_action)),
#            'phi': (jax.grad(scalar_action)),
        }

        def force_func(fields):
            return {'phi': self.grads['phi'](fields['phi']) }

        self.forces = force_func



S2test = ScalarAction({'phi': phi_field}, params={'lamb': 1.1})

print(S2test)

In [14]:
%time S2test.S()

CPU times: user 17.9 ms, sys: 3.31 ms, total: 21.2 ms
Wall time: 18.4 ms


Array(-455680., dtype=float32)

In [15]:
F2test = S2test.get_forces(recompute=False)

In [16]:
gg = jax.grad(scalar_action)

In [17]:
%time gg(phi_field)

CPU times: user 119 ms, sys: 15.3 ms, total: 134 ms
Wall time: 121 ms


In [18]:
%time F2test(S2test.fields)

CPU times: user 74.3 ms, sys: 14.3 ms, total: 88.6 ms
Wall time: 72.9 ms


{'phi': <lfox.lattice.LatticeField at 0x109a6ca90>}

In [19]:
HMCTest = lhmc.HMCEvolver(S2test, 0, itest)
print(HMCTest)

In [23]:
%%time

for _ in range(100):
    HMCTest.evolve(warmup=True)

for _ in range(100):
    HMCTest.evolve()

CPU times: user 3.23 s, sys: 573 ms, total: 3.81 s
Wall time: 3.14 s


In [22]:
%%prun -s cumulative
HMCTest.evolve()

         4234 function calls (4210 primitive calls) in 0.041 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.041    0.041 {built-in method builtins.exec}
        1    0.000    0.000    0.040    0.040 <string>:1(<module>)
        1    0.029    0.029    0.040    0.040 hmc.py:298(evolve)
        1    0.000    0.000    0.008    0.008 hmc.py:266(mom_refresh)
       14    0.000    0.000    0.006    0.000 core.py:388(bind_with_trace)
       14    0.000    0.000    0.006    0.000 core.py:820(process_primitive)
        2    0.000    0.000    0.006    0.003 traceback_util.py:162(reraise_with_filtered_traceback)
        2    0.000    0.000    0.006    0.003 pjit.py:251(cache_miss)
        2    0.000    0.000    0.006    0.003 pjit.py:160(_python_pjit_helper)
        1    0.000    0.000    0.005    0.005 random.py:621(normal)
        2    0.000    0.000    0.004    0.002 core.py:2590(bind)
        2  

In [120]:
print(HMCTest.monitor['P_acc'])

[Array(3.478942e-35, dtype=float32), Array(5.380186e-32, dtype=float32), Array(7.187782e-28, dtype=float32), Array(2.3802664e-26, dtype=float32), Array(3.0774976e-19, dtype=float32), Array(1.3656312e-19, dtype=float32), Array(2.882351e-13, dtype=float32), Array(5.9821283e-15, dtype=float32), Array(1.691898e-10, dtype=float32), Array(6.431394e-14, dtype=float32), Array(1.067704e-06, dtype=float32), Array(4.691164e-08, dtype=float32), Array(1.0130094e-05, dtype=float32), Array(3.653482e-08, dtype=float32), Array(1.067704e-06, dtype=float32), Array(2.6995784e-07, dtype=float32), Array(1.3709591e-06, dtype=float32), Array(1.5535002e-06, dtype=float32), Array(1.2098672e-06, dtype=float32), Array(5.4222483e-06, dtype=float32), Array(1.4449802e-07, dtype=float32)]


In [109]:
import matplotlib.pyplot as plt

plt.plot(HMCTest.monitor['delta_H'])

ModuleNotFoundError: No module named 'matplotlib'

In [103]:
print(HMCTest.field_chain['phi'][0].field)
print(HMCTest.action.fields['phi'].field)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  ...

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 