In [1]:
import lfox
import lfox.lattice as lat
import jax
import jax.numpy as jnp

import numpy as np

In [2]:
d = 4
L = 16

In [3]:
MyLat = lat.SquareLattice(dims=((L,)*d))
MyLat

In [11]:
key = jax.random.PRNGKey(1)
m=20000; n=10000
x = jax.random.normal(key, (m,n))
y = jax.random.normal(key, (n,))

In [12]:
%timeit jnp.dot(y, x.T).block_until_ready()

136 ms ± 1.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
flop_count = 2*m*n
T = 0.136
GF = flop_count / 1e9 / T
GF

2.941176470588235

In [4]:
phi_field = lat.LatticeField(MyLat)
phi_field.F = np.ones_like(phi_field.F)
phi_field.F[0,0] = 0.
phi_field.F = jnp.array(phi_field.F)
print(phi_field.F, phi_field)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  ...

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 

I0000 00:00:1696015947.967524       1 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.


In [5]:
phi_field.nn_field(0)

Array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
    

In [6]:
p2 = phi_field.copy()
p2 += phi_field
p2.field

Array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.]],

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.]],

        ...,

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
    

In [13]:
print(p2)
p2 += phi_field
print(p2, p2.field)

<lfox.lattice.LatticeField object at 0x1487c6550> [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   ...
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]]

  [[5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   ...
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]]

  ...

  [[5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   ...
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]]

  [[5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   ...
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]]

  [[5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   [5. 5. 5. ... 5. 5. 5.]
   ...


In [14]:
@jax.jit
def scalar_action(phi):
    S = 0.0
    F = phi.field
    for ax in range(d):
        S -= 2 * jnp.sum(F * phi.nn_field(ax))
    phi2 = F**2
    S += jnp.sum(phi2)
    S += jnp.sum( (phi2-1)**2 )

    return S

In [15]:
sum(jnp.array([1,2]), jnp.array([3,4]))

Array([6, 7], dtype=int32)

In [16]:
%time scalar_action(phi_field)

CPU times: user 43.1 ms, sys: 7.98 ms, total: 51.1 ms
Wall time: 42.3 ms


Array(-455680., dtype=float32)

In [17]:
T = 0.002  # 9 ms
flops = (L**d) * (3 + 2*d) + (L**d - 1) * 3
print(flops, flops/T/1e9)  # GFlops

917501 0.4587505


In [18]:
import lfox.evolution.hmc as lhmc

In [19]:
itest = lhmc.LeapfrogIntegrator(0.005, 200)
print(itest)

In [20]:
class ScalarAction(lhmc.Action):
    @staticmethod
    def _Sjax(phi):
        return scalar_action(phi)

    def _compute_forces(self):
        print("compute forces")
        self.grads = {
            'phi': jax.jit(jax.grad(scalar_action)),
#            'phi': (jax.grad(scalar_action)),
        }

        def force_func(fields):
            return {'phi': self.grads['phi'](fields['phi']) }

        self.forces = force_func



S2test = ScalarAction({'phi': phi_field}, params={'lamb': 1.1})

print(S2test)

In [21]:
%time S2test.S()

CPU times: user 17.6 ms, sys: 4.2 ms, total: 21.8 ms
Wall time: 19.5 ms


Array(-455680., dtype=float32)

In [22]:
F2test = S2test.get_forces(recompute=False)

compute forces


In [23]:
gg = jax.grad(scalar_action)

In [24]:
%time gg(phi_field)

CPU times: user 107 ms, sys: 16.4 ms, total: 124 ms
Wall time: 113 ms


In [25]:
%time F2test(S2test.fields)

CPU times: user 64.9 ms, sys: 18.5 ms, total: 83.4 ms
Wall time: 68.2 ms


{'phi': <lfox.lattice.LatticeField at 0x13846e850>}

In [26]:
HMCTest = lhmc.HMCEvolver(S2test, 0, itest)
print(HMCTest)

In [27]:
print(HMCTest.H())
HMCTest.mom_refresh()
print(HMCTest.H())

-455680.0
-422994.94


In [28]:
from functools import partial

@partial(jax.jit, static_argnums=(0,))
def heatbath(shape, key):
    key, subkey = jax.random.split(key)
    return key, jax.random.normal(subkey, shape=shape)

def heatbath_nojit(shape, key):
    key, subkey = jax.random.split(key)
    return key, jax.random.normal(subkey, shape=shape)    

heatbath((4,4), jax.random.PRNGKey(0))

(Array([4146024105,  967050713], dtype=uint32),
 Array([[ 0.20820075, -1.0580498 , -0.2937458 , -0.44117242],
        [ 0.2366985 , -0.03426379, -1.002556  ,  1.1560112 ],
        [-0.538138  , -0.48968914,  0.2493904 , -1.4128864 ],
        [ 1.8543109 ,  0.22756508,  0.4975155 , -2.0896842 ]],      dtype=float32))

In [29]:
%time heatbath((4,4), jax.random.PRNGKey(7))

CPU times: user 1.44 ms, sys: 474 µs, total: 1.92 ms
Wall time: 1.7 ms


(Array([966301609, 989289821], dtype=uint32),
 Array([[ 1.7575002 , -0.85857755, -0.12954493,  0.66024953],
        [ 0.5250321 , -0.93147874, -2.2382581 ,  0.17728978],
        [-0.51548475,  0.30545995, -0.19785893,  1.9608958 ],
        [-2.613401  , -1.2065986 ,  1.0774857 ,  0.6525771 ]],      dtype=float32))

In [30]:
%time heatbath_nojit((4,4), jax.random.PRNGKey(7))

CPU times: user 97.9 ms, sys: 16.5 ms, total: 114 ms
Wall time: 112 ms


(Array([966301609, 989289821], dtype=uint32),
 Array([[ 1.7575002 , -0.85857755, -0.12954493,  0.66024953],
        [ 0.5250321 , -0.93147874, -2.2382581 ,  0.17728978],
        [-0.51548475,  0.30545995, -0.19785893,  1.9608958 ],
        [-2.613401  , -1.2065986 ,  1.0774857 ,  0.6525771 ]],      dtype=float32))

In [31]:
HMCTest._KE([HMCTest.pi_fields['phi'].field ])

Array(32685.074, dtype=float32)

In [32]:
HMCTest.evolve(warmup=True)

HMCTest.field_chain['phi'][-1].field

Array([[[[1.5842308, 2.3482378, 2.0989695, ..., 2.6701407, 1.816719 ,
          2.033083 ],
         [1.8539345, 3.4177356, 2.3555226, ..., 1.7800941, 1.4599859,
          1.9843284],
         [1.6953952, 2.5686846, 1.8046598, ..., 2.855406 , 1.8623399,
          1.832392 ],
         ...,
         [1.5842626, 1.7091143, 2.2423515, ..., 1.7114639, 1.7674656,
          1.6948197],
         [1.438889 , 1.5586451, 2.0299191, ..., 2.1371083, 1.7568862,
          1.5933629],
         [1.3623953, 1.798198 , 2.160663 , ..., 1.8388346, 1.7837641,
          1.6356587]],

        [[1.7445335, 1.78251  , 1.5600995, ..., 1.8239579, 1.6262571,
          1.7449439],
         [1.5299996, 1.6586915, 1.6256638, ..., 1.6896449, 1.5576786,
          1.5507022],
         [1.7360417, 1.794521 , 1.6981859, ..., 1.5714167, 1.460866 ,
          1.7982099],
         ...,
         [1.6881698, 1.5689223, 1.5251666, ..., 1.6199319, 1.7144362,
          1.5775443],
         [1.6478869, 1.9338381, 1.7159355, ..., 1.

In [33]:
%%time

for _ in range(10):
    HMCTest.evolve(warmup=True)

for _ in range(10):
    HMCTest.evolve()

CPU times: user 1.22 s, sys: 128 ms, total: 1.34 s
Wall time: 1.26 s


In [33]:
%%prun -s cumulative
HMCTest.evolve(warmup=False)

         2102 function calls (2091 primitive calls) in 0.090 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.090    0.090 {built-in method builtins.exec}
        1    0.000    0.000    0.090    0.090 <string>:1(<module>)
        1    0.081    0.081    0.090    0.090 hmc.py:335(evolve)
        1    0.005    0.005    0.005    0.005 hmc.py:291(mom_refresh)
        2    0.000    0.000    0.002    0.001 hmc.py:277(H)
        1    0.000    0.000    0.001    0.001 hmc.py:188(copy_fields)
        1    0.000    0.000    0.001    0.001 lattice.py:127(copy)
        1    0.000    0.000    0.001    0.001 lattice.py:119(__copy__)
        1    0.000    0.000    0.001    0.001 lax_numpy.py:2093(copy)
        1    0.000    0.000    0.001    0.001 lax_numpy.py:2002(array)
        2    0.000    0.000    0.001    0.001 hmc.py:75(S)
        2    0.000    0.000    0.001    0.001 hmc.py:137(_S)
        6    0.00

In [30]:
HMCTest.monitor

{'delta_H': [Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32),
  Array(0., dtype=float32)],
 'P_acc': [1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0,
  1.0]}

In [23]:
import matplotlib.pyplot as plt

plt.plot(HMCTest.monitor['delta_H'])

ModuleNotFoundError: No module named 'matplotlib'

In [31]:
print(HMCTest.field_chain['phi'][0].field)
print(HMCTest.action.fields['phi'].field)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  ...

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 

In [25]:
@jax.jit
def mag(phi):
    return jnp.sum(phi.field)

def mag_obs(fields, params):
    m = mag(fields['phi'])
    m2 = m**2
    m4 = m**4

    return jnp.array([m, m2, m4])

In [26]:
mag_obs({'phi': phi_field}, {})

Array([6.5280000e+04, 4.2614784e+09, 1.8160198e+19], dtype=float32)

In [29]:
HMCTest = lhmc.HMCEvolver(S2test, 0, itest, observables={'mag': [mag_obs, 2]})
print(HMCTest)

In [78]:
for _ in range(20):
    HMCTest.evolve(warmup=True)

In [79]:
print(HMCTest.traj_chain)

HMCTest.obs_chain

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171]


{'mag': [Array([1.24907086e+05, 1.56017797e+10, 2.43415531e+20], dtype=float32),
  Array([1.24907086e+05, 1.56017797e+10, 2.43415531e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=flo