In [1]:
import lfox
import lfox.lattice as lat
import jax
import jax.numpy as jnp

import numpy as np

In [2]:
d = 4
L = 16

In [3]:
MyLat = lat.SquareLattice(dims=((L,)*d))
MyLat

In [4]:
phi_field = lat.LatticeField(MyLat)
phi_field.field = np.ones_like(phi_field.field)
phi_field.field[0,0] = 0.
phi_field.field = jnp.array(phi_field.field)
print(phi_field.field, phi_field)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  ...

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 

In [5]:
phi_field.nn_field(0)

Array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
    

In [6]:
p2 = phi_field.copy()
p2 += phi_field
p2.field

Array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.]],

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.]],

        ...,

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
    

In [7]:
print(p2)
p2 += phi_field
print(p2, p2.field)

<lfox.lattice.LatticeField object at 0x103e884d0> [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  ...

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...


In [8]:
@jax.jit
def scalar_action(phi):
    S = 0.0
    F = phi.field
    for ax in range(d):
        S -= 2 * jnp.sum(F * phi.nn_field(ax))
    phi2 = F**2
    S += jnp.sum(phi2)
    S += jnp.sum( (phi2-1)**2 )

    return S

In [9]:
sum(jnp.array([1,2]), jnp.array([3,4]))

Array([6, 7], dtype=int32)

In [10]:
%time scalar_action(phi_field)

CPU times: user 40.7 ms, sys: 8.67 ms, total: 49.4 ms
Wall time: 40.2 ms


Array(-455680., dtype=float32)

In [11]:
T = 0.002  # 9 ms
flops = (L**d) * (3 + 2*d) + (L**d - 1) * 3
print(flops, flops/T/1e9)  # GFlops

917501 0.4587505


In [12]:
import lfox.evolution.hmc as lhmc

In [13]:
itest = lhmc.LeapfrogIntegrator(0.005, 200)
print(itest)

In [14]:
class ScalarAction(lhmc.Action):
    @staticmethod
    def _Sjax(phi):
        return scalar_action(phi)

    def _compute_forces(self):
        print("compute forces")
        self.grads = {
            'phi': jax.jit(jax.grad(scalar_action)),
#            'phi': (jax.grad(scalar_action)),
        }

        def force_func(fields):
            return {'phi': self.grads['phi'](fields['phi']) }

        self.forces = force_func



S2test = ScalarAction({'phi': phi_field}, params={'lamb': 1.1})

print(S2test)

In [15]:
%time S2test.S()

CPU times: user 5.08 ms, sys: 845 µs, total: 5.92 ms
Wall time: 5.11 ms


Array(-455680., dtype=float32)

In [16]:
F2test = S2test.get_forces(recompute=False)

compute forces


In [17]:
gg = jax.grad(scalar_action)

In [18]:
%time gg(phi_field)

CPU times: user 105 ms, sys: 13.6 ms, total: 118 ms
Wall time: 107 ms


In [19]:
%time F2test(S2test.fields)

CPU times: user 60.1 ms, sys: 13.3 ms, total: 73.3 ms
Wall time: 57.2 ms


{'phi': <lfox.lattice.LatticeField at 0x10f219050>}

In [20]:
HMCTest = lhmc.HMCEvolver(S2test, 0, itest)
print(HMCTest)

In [21]:
%%time

for _ in range(10):
    HMCTest.evolve(warmup=True)

for _ in range(10):
    HMCTest.evolve()

CPU times: user 11.3 s, sys: 1.52 s, total: 12.8 s
Wall time: 10.7 s


In [22]:
%%prun -s cumulative
HMCTest.evolve()

         2639 function calls (2625 primitive calls) in 0.060 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.060    0.060 {built-in method builtins.exec}
        1    0.000    0.000    0.060    0.060 <string>:1(<module>)
        1    0.056    0.056    0.060    0.060 hmc.py:312(evolve)
        1    0.000    0.000    0.003    0.003 hmc.py:280(mom_refresh)
        9    0.000    0.000    0.002    0.000 core.py:388(bind_with_trace)
        9    0.000    0.000    0.002    0.000 core.py:820(process_primitive)
        1    0.000    0.000    0.002    0.002 random.py:621(normal)
        1    0.000    0.000    0.002    0.002 traceback_util.py:162(reraise_with_filtered_traceback)
        1    0.000    0.000    0.002    0.002 pjit.py:251(cache_miss)
        1    0.000    0.000    0.002    0.002 pjit.py:160(_python_pjit_helper)
     11/6    0.000    0.000    0.002    0.000 profiler.py:311(wrapper)
     

In [23]:
print(HMCTest.monitor['P_acc'])

[Array(0.00071017, dtype=float32), Array(0.036425, dtype=float32), Array(0.00141235, dtype=float32), Array(22.759895, dtype=float32), Array(1.8925506e-05, dtype=float32), Array(37.524723, dtype=float32), Array(0.47236654, dtype=float32), Array(0.00080473, dtype=float32), Array(0.2865048, dtype=float32), Array(0.13533528, dtype=float32), Array(1.6487212, dtype=float32), Array(0.09301449, dtype=float32), Array(5.0784187, dtype=float32), Array(0.00360656, dtype=float32), Array(0.00360656, dtype=float32), Array(0.0010333, dtype=float32), Array(0.082085, dtype=float32), Array(0.19691168, dtype=float32), Array(1.14789e-05, dtype=float32), Array(0.03421812, dtype=float32), Array(1.2840254, dtype=float32)]


In [24]:
import matplotlib.pyplot as plt

plt.plot(HMCTest.monitor['delta_H'])

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
print(HMCTest.field_chain['phi'][0].field)
print(HMCTest.action.fields['phi'].field)

In [25]:
@jax.jit
def mag(phi):
    return jnp.sum(phi.field)

def mag_obs(fields, params):
    m = mag(fields['phi'])
    m2 = m**2
    m4 = m**4

    return jnp.array([m, m2, m4])

In [26]:
mag_obs({'phi': phi_field}, {})

Array([6.5280000e+04, 4.2614784e+09, 1.8160198e+19], dtype=float32)

In [29]:
HMCTest = lhmc.HMCEvolver(S2test, 0, itest, observables={'mag': [mag_obs, 2]})
print(HMCTest)

In [78]:
for _ in range(20):
    HMCTest.evolve(warmup=True)

In [79]:
print(HMCTest.traj_chain)

HMCTest.obs_chain

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171]


{'mag': [Array([1.24907086e+05, 1.56017797e+10, 2.43415531e+20], dtype=float32),
  Array([1.24907086e+05, 1.56017797e+10, 2.43415531e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=float32),
  Array([1.2681570e+05, 1.6082222e+10, 2.5863787e+20], dtype=flo