In [1]:
import lfox
import lfox.lattice as lat
import jax
import jax.numpy as jnp

import numpy as np

In [78]:
d = 4
L = 16

In [79]:
MyLat = lat.SquareLattice(dims=((L,)*d))
MyLat

In [80]:
phi_field = lat.LatticeField(MyLat)
phi_field.field = np.ones_like(phi_field.field)
phi_field.field[0,0] = 0.
phi_field.field = jnp.array(phi_field.field)
print(phi_field.field, phi_field)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  ...

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 

In [81]:
phi_field.nn_field(0)

Array([[[[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
         ...,
         [1., 1., 1., ..., 1., 1., 1.],
         [1., 1., 1., ..., 1., 1., 1.],
    

In [82]:
p2 = phi_field.copy()
p2 += phi_field
p2.field

Array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]],

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.]],

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.]],

        ...,

        [[2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
         ...,
         [2., 2., 2., ..., 2., 2., 2.],
         [2., 2., 2., ..., 2., 2., 2.],
    

In [83]:
print(p2)
p2 += phi_field
print(p2, p2.field)

<lfox.lattice.LatticeField object at 0x281ed0a50> [[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  ...

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]]

  [[3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   [3. 3. 3. ... 3. 3. 3.]
   ...


In [84]:
@jax.jit
def scalar_action(phi):
    S = 0.0
    F = phi.field
    for ax in range(d):
        S -= 2 * jnp.sum(F * phi.nn_field(ax))
    phi2 = F**2
    S += jnp.sum(phi2)
    S += jnp.sum( (phi2-1)**2 )

    return S

In [85]:
sum(jnp.array([1,2]), jnp.array([3,4]))

Array([6, 7], dtype=int32)

In [87]:
%time scalar_action(phi_field)

CPU times: user 1.44 ms, sys: 281 µs, total: 1.72 ms
Wall time: 831 µs


Array(-455680., dtype=float32)

In [88]:
import lfox.evolution.hmc as lhmc

In [111]:
itest = lhmc.LeapfrogIntegrator(0.02, 50)
print(itest)

In [192]:
class ScalarAction(lhmc.Action):
    @staticmethod
    def _Sjax(phi):
        return scalar_action(phi)

    def _compute_forces(self):
        self.grads = {
            'phi': jax.jit(jax.grad(scalar_action)),
#            'phi': (jax.grad(scalar_action)),
        }

        def force_func(fields):
            return {'phi': self.grads['phi'](fields['phi']) }

        self.forces = force_func



S2test = ScalarAction({'phi': phi_field}, params={'lamb': 1.1})

print(S2test)

In [194]:
%time S2test.S()

CPU times: user 1.83 ms, sys: 1.13 ms, total: 2.96 ms
Wall time: 1.35 ms


Array(-455680., dtype=float32)

In [195]:
F2test = S2test.get_forces(recompute=False)

compile


In [175]:
gg = jax.grad(scalar_action)

In [162]:
%time gg(phi_field)

CPU times: user 9.09 ms, sys: 4.17 ms, total: 13.3 ms
Wall time: 8.62 ms


In [200]:
%time F2test(S2test.fields)

CPU times: user 2.61 ms, sys: 1.24 ms, total: 3.85 ms
Wall time: 1.12 ms


{'phi': <lfox.lattice.LatticeField at 0x358e33fd0>}

In [169]:
HMCTest = lhmc.HMCEvolver(S2test, 0, itest)
print(HMCTest)

In [170]:
%%time

for _ in range(10):
    HMCTest.evolve(warmup=True)

for _ in range(10):
    HMCTest.evolve()

CPU times: user 35 s, sys: 6.1 s, total: 41.1 s
Wall time: 30.2 s


In [203]:
%%prun -s cumulative
HMCTest.evolve()

         3247060 function calls (3172123 primitive calls) in 2.320 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    2.363    2.363 {built-in method builtins.exec}
        1    0.000    0.000    2.363    2.363 <string>:1(<module>)
        1    0.000    0.000    2.363    2.363 hmc.py:291(evolve)
    305/3    0.000    0.000    2.357    0.786 traceback_util.py:162(reraise_with_filtered_traceback)
    305/3    0.001    0.000    2.357    0.786 pjit.py:251(cache_miss)
    305/3    0.001    0.000    2.357    0.786 pjit.py:160(_python_pjit_helper)
   169/12    0.001    0.000    2.334    0.194 profiler.py:311(wrapper)
      305    0.001    0.000    2.283    0.007 core.py:2590(bind)
  921/468    0.001    0.000    2.278    0.005 core.py:388(bind_with_trace)
       15    0.000    0.000    2.123    0.142 core.py:820(process_primitive)
        3    0.000    0.000    2.122    0.707 pjit.py:1188(_pjit_call_im

In [120]:
print(HMCTest.monitor['P_acc'])

[Array(3.478942e-35, dtype=float32), Array(5.380186e-32, dtype=float32), Array(7.187782e-28, dtype=float32), Array(2.3802664e-26, dtype=float32), Array(3.0774976e-19, dtype=float32), Array(1.3656312e-19, dtype=float32), Array(2.882351e-13, dtype=float32), Array(5.9821283e-15, dtype=float32), Array(1.691898e-10, dtype=float32), Array(6.431394e-14, dtype=float32), Array(1.067704e-06, dtype=float32), Array(4.691164e-08, dtype=float32), Array(1.0130094e-05, dtype=float32), Array(3.653482e-08, dtype=float32), Array(1.067704e-06, dtype=float32), Array(2.6995784e-07, dtype=float32), Array(1.3709591e-06, dtype=float32), Array(1.5535002e-06, dtype=float32), Array(1.2098672e-06, dtype=float32), Array(5.4222483e-06, dtype=float32), Array(1.4449802e-07, dtype=float32)]


In [109]:
import matplotlib.pyplot as plt

plt.plot(HMCTest.monitor['delta_H'])

ModuleNotFoundError: No module named 'matplotlib'

In [103]:
print(HMCTest.field_chain['phi'][0].field)
print(HMCTest.action.fields['phi'].field)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  ...

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]]

  [[1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 1.]
   ...
   [1. 1. 1. ... 1. 1. 1.]
   [1. 1. 1. ... 1. 1. 